const assert=require('node:assert/strict'),m=require('./model.js');
const memory={raw:null,getItem(){return this.raw},setItem(k,v){this.raw=v}};
let jobs=m.add([],' 라이트랩 ',' 개발자 ','one');
assert.equal(jobs[0].company,'라이트랩');
m.save(memory,jobs);assert.deepEqual(m.load(memory),jobs);
for(const s of m.statuses){jobs=m.transition(jobs,'one',s);assert.equal(jobs[0].status,s);}
assert.throws(()=>m.add(jobs,' ','role','two'));
assert.throws(()=>m.transition(jobs,'missing','지원'));
assert.throws(()=>m.transition(jobs,'one','잘못된 상태'));
assert.throws(()=>m.validate([...jobs,...jobs]));
memory.raw='{broken';assert.throws(()=>m.load(memory));assert.equal(memory.raw,'{broken');
assert.throws(()=>m.save({setItem(){throw Error('quota')}},jobs));
assert.equal(jobs[0].status,'종료');
console.log('PASS: trim, persistence, states, blank input, unknown id/status, duplicate, corrupt storage preservation, save failure');
const fixture=[{id:'a',company:'LightLab',role:'프론트엔드 개발자',status:'관심'},{id:'b',company:'모닝',role:'프로덕트 디자이너',status:'면접'},{id:'c',company:'라이트',role:'백엔드 개발자',status:'면접'}];
const before=JSON.stringify(fixture);
assert.deepEqual(m.selectJobs(fixture,'all',' lightLAB ').map(x=>x.id),['a']);
assert.deepEqual(m.selectJobs(fixture,'all','개발자').map(x=>x.id),['a','c']);
assert.deepEqual(m.selectJobs(fixture,'면접','개발자').map(x=>x.id),['c']);
assert.deepEqual(m.selectJobs(fixture,'관심','디자이너'),[]);
assert.deepEqual(m.selectJobs(fixture,'all','  '),fixture);
assert.deepEqual(m.selectJobs(fixture,'면접','').map(x=>x.id),['b','c']);
assert.equal(JSON.stringify(fixture),before);
console.log('PASS AF-104: company/role, case, trimming, status AND, empty query/results, data unchanged');
assert.equal(typeof m.parseBackup,'function','백업 검증 함수가 필요합니다.');
const backup=JSON.stringify({version:1,jobs:fixture});
assert.deepEqual(m.parseBackup(backup),fixture);
assert.deepEqual(m.parseBackup('{"version":1,"jobs":[]}'),[]);
for(const bad of ['{broken','[]','{"version":2,"jobs":[]}',JSON.stringify({version:1,jobs:[fixture[0],fixture[0]]}),JSON.stringify({version:1,jobs:[{...fixture[0],status:'미정'}]}),JSON.stringify({version:1,jobs:[{...fixture[0],id:''}]}),JSON.stringify({version:1,jobs:Array.from({length:201},(_,i)=>({...fixture[0],id:String(i)}))})])assert.throws(()=>m.parseBackup(bad));
assert.throws(()=>m.parseBackup(' '.repeat(1024*1024+1)));
const unsafe={...fixture[0],hidden:'discard'};
assert.deepEqual(m.parseBackup(JSON.stringify({version:1,jobs:[unsafe]})),[fixture[0]]);
assert.deepEqual(m.remove(fixture,'b').map(x=>x.id),['a','c']);
assert.throws(()=>m.remove(fixture,'missing'));
assert.equal(JSON.stringify(fixture),before);
const stable={raw:JSON.stringify(fixture),getItem(){return this.raw},setItem(){throw Error('quota')}};
assert.throws(()=>m.save(stable,m.parseBackup(backup)));
assert.equal(stable.raw,JSON.stringify(fixture));
console.log('PASS AF-105/106: backup validation/version/size/duplicates/limits/projection, immutable deletion, failed-save preservation');
