const assert=require('node:assert/strict'),m=require('./model.js');
const memory={raw:null,getItem(){return this.raw},setItem(k,v){this.raw=v}};
let jobs=m.add([],' 라이트랩 ',' 개발자 ','one');
assert.equal(jobs[0].company,'라이트랩');
m.save(memory,jobs);assert.deepEqual(m.load(memory),jobs);
for(const s of m.statuses){jobs=m.transition(jobs,'one',s);assert.equal(jobs[0].status,s);}
assert.throws(()=>m.add(jobs,' ','role','two'));
assert.throws(()=>m.transition(jobs,'missing','지원'));
assert.throws(()=>m.transition(jobs,'one','잘못된 상태'));
assert.throws(()=>m.validate([...jobs,...jobs]));
memory.raw='{broken';assert.throws(()=>m.load(memory));assert.equal(memory.raw,'{broken');
assert.throws(()=>m.save({setItem(){throw Error('quota')}},jobs));
assert.equal(jobs[0].status,'종료');
console.log('PASS: trim, persistence, states, blank input, unknown id/status, duplicate, corrupt storage preservation, save failure');
const fixture=[{id:'a',company:'LightLab',role:'프론트엔드 개발자',status:'관심'},{id:'b',company:'모닝',role:'프로덕트 디자이너',status:'면접'},{id:'c',company:'라이트',role:'백엔드 개발자',status:'면접'}];
const before=JSON.stringify(fixture);
assert.deepEqual(m.selectJobs(fixture,'all',' lightLAB ').map(x=>x.id),['a']);
assert.deepEqual(m.selectJobs(fixture,'all','개발자').map(x=>x.id),['a','c']);
assert.deepEqual(m.selectJobs(fixture,'면접','개발자').map(x=>x.id),['c']);
assert.deepEqual(m.selectJobs(fixture,'관심','디자이너'),[]);
assert.deepEqual(m.selectJobs(fixture,'all','  '),fixture);
assert.deepEqual(m.selectJobs(fixture,'면접','').map(x=>x.id),['b','c']);
assert.equal(JSON.stringify(fixture),before);
console.log('PASS AF-104: company/role, case, trimming, status AND, empty query/results, data unchanged');
