"""Accessible course figures. Numerical timelines derive from the lesson source."""
import base64
import html
import re
from pathlib import Path


def figure(number, title, body, caption):
    return f'<figure class="learning-figure"><div class="figure-label">FIGURE {number}</div><h3>{title}</h3>{body}<figcaption>{caption}</figcaption></figure>'


def steps(items):
    return '<ol class="visual-steps">'+''.join(f'<li><span class="step-number">{i:02}</span><strong>{a}</strong><p>{b}</p></li>' for i,(a,b) in enumerate(items,1))+'</ol>'


def build_visuals(root):
    image=base64.b64encode((root/'course/assets/project-journey.png').read_bytes()).decode()
    result={}
    result['journey']=figure('01','하나의 아이디어가 완성품이 되는 네 장면',f'<img class="journey-art" src="data:image/png;base64,{image}" width="2172" height="724" alt="학생이 화면을 스케치하고, 목업을 만든 뒤, 코드와 데이터 저장을 연결해 다른 사람이 사용하는 결과물로 전달하는 그림">'+steps([('1주 · 정하기','사용자 한 명, 문제 하나, 첫 실행'),('2주 · 연결하기','목업에서 규칙을 찾고 실제 동작 구현'),('3주 · 확인하기','실패를 재현하고 수정 근거 확보'),('4주 · 전달하기','다른 세션에서 사용하고 증거 제출')]),'AI 생성 개념 삽화입니다. 학생마다 제품은 달라도 문제 → 목업 → 구현 → 실제 사용의 흐름은 공유합니다.')
    bars=[]
    for week in range(1,5):
        src=(root/f'course/week{week}.md').read_text()
        rows=re.findall(r'^\| (\d+)–(\d+) \| ([^|]+) \|',src,re.M)
        assert rows and int(rows[0][0])==0 and int(rows[-1][1])==120
        assert all(int(rows[i][1])==int(rows[i+1][0]) for i in range(len(rows)-1))
        segments=[];legend=[]
        for i,(start,end,label) in enumerate(rows):
            duration=int(end)-int(start);label=label.strip();esc=html.escape(label)
            segments.append(f'<span class="time-segment tone-{i%4}" style="flex:{duration}" title="{esc}: {duration}분"><b>{duration}</b></span>')
            legend.append(f'<li><b>{start}–{end}분</b> {esc}</li>')
        bars.append(f'<div class="time-row"><a href="#week{week}">{week}주차</a><div class="time-bar" role="img" aria-label="{week}주차 총 120분. 세부 내역은 아래 표에 있습니다.">'+''.join(segments)+'</div><strong>120분</strong></div><details class="time-detail"><summary>'+str(week)+'주차 시간 내역</summary><ul>'+''.join(legend)+'</ul></details>')
    result['time']=figure('02','8시간을 어떻게 쓰나요?','<div class="axis-label"><span>0분</span><span>60분</span><span>120분</span></div>'+''.join(bars),'출처: 이 교재 1–4주차 진행표. 막대 길이는 실제 배정 시간에 비례하며 숫자 단위는 분입니다. 색은 인접 활동 구분용입니다. 총 480분에는 휴식이 포함됩니다.')
    result['layers']=figure('03','모델을 고르는 것과 작업 환경을 고르는 것은 다릅니다','''<div class="layer-map"><div class="layer-user"><strong>내 프로젝트 계약</strong><span>누가 · 어떤 결과 · 어떤 위험 · 얼마의 예산</span></div><div class="layer-pair"><div><small>수행 지침</small><strong>한국어 스킬</strong><p>지금 단계의 절차와 완료 조건</p></div><div><small>실행 환경</small><strong>코딩 에이전트</strong><p>파일 · 터미널 · 브라우저 · 권한</p></div></div><div class="layer-user"><strong>모델 + 사고 설정</strong><span>판단과 생성에 필요한 능력·맥락·추론량</span></div><div class="layer-pair"><div><strong>프로바이더</strong><p>접근 경로 · 과금 · 데이터 처리 조건</p></div><div><strong>실행 증거</strong><p>테스트 · 화면 · 저장 · 사용 결과</p></div></div></div>''','읽는 순서: 프로젝트 계약에서 출발해 지침과 실행 도구를 갖추고 모델을 선택합니다. 같은 모델이어도 도구·맥락·권한이 달라지면 결과가 달라집니다.')
    result['levels']=figure('04','완료 기준은 사용 범위와 목적에 맞춥니다','''<div class="completion-grid"><div><span>가설 검증</span><h4>PoC</h4><p>실험 결과와 진행·중단 판단</p><b>질문: 가능한가?</b></div><div><span>나의 문제 해결</span><h4>개인 완성품</h4><p>핵심 흐름·저장·재실행·사용법</p><b>질문: 내가 다시 쓸 수 있는가?</b></div><div><span>제한된 실제 사용자</span><h4>MVP</h4><p>문제 해결·접근 경계·피드백</p><b>질문: 사용자가 가치를 얻는가?</b></div><div><span>지속적으로 운영</span><h4>운영 서비스</h4><p>위험에 맞는 복구·관찰·책임</p><b>질문: 문제가 나도 대응 가능한가?</b></div></div><div class="figure-callout">공통 바닥: 실제 위험 확인 + 결과의 정직한 기록. 개인용이라도 원본 삭제·결제·민감자료 위험은 생략하지 않습니다.</div>''','네 칸은 성능 순위나 반드시 거치는 승급 단계가 아닙니다. PoC·MVP는 제품 단계이며 개인용은 사용 범위입니다. 학생은 사용 범위와 목표 단계를 함께 적습니다.')
    result['prototype']=figure('05','버튼 하나에서 설계를 역으로 도출해 봅니다','''<noscript><p>이 목업의 버튼 실습은 JavaScript가 필요합니다. 아래 설명과 정적 화면으로 규칙을 확인하세요.</p></noscript><div class="prototype-layout"><div class="mock-browser"><div class="mock-top"><span>DEMO / 문의 정리</span><b>임시 데이터</b></div><div class="mock-content"><small>문의 #001 · 예시 데이터</small><h4>배송 일정 문의</h4><p>완료 버튼을 누르면 어떤 약속이 생길까요?</p><span id="demo-status" class="status-pill">미처리</span><div class="mock-actions"><button type="button" id="demo-complete">처리 완료</button><button type="button" id="demo-reset">초기화</button></div><p class="demo-note">교육용 목업입니다. 서버·DB에 저장하지 않으며 새로고침하면 초기화됩니다.</p></div></div><ol class="derived-contracts"><li><strong>행동 → 업무 규칙</strong><span>미처리만 완료로 전환. 중복 실행은?</span></li><li><strong>규칙 → 함수 / API 계약</strong><span>입력: 문의 ID · 결과: 변경된 상태</span></li><li><strong>계약 → 데이터</strong><span>문의 ID · 상태 · 필요한 경우 완료 시각</span></li><li><strong>데이터 → 검증</strong><span>새로고침 후 유지? 저장 실패? 권한 거부?</span></li></ol></div><p id="demo-explanation" class="figure-callout" role="status">버튼을 눌러 보세요. 화면에서 바뀌는 것과 실제 저장되는 것을 구분하는 실습입니다.</p>''','작동하는 교육용 목업입니다. 버튼 상태가 바뀌어도 영속 저장은 구현되지 않았습니다. 이 간극을 찾아내는 것이 2주차 설계 실습의 출발점입니다.')
    result['pyramid']=figure('06','화면에서 시작해 필요한 내부 구조로 좁혀 갑니다','''<div class="inverse-pyramid"><div><strong>사용 경험 · 시안</strong><span>사용자가 보고 조작할 결과</span></div><div><strong>행동 · 업무 규칙</strong><span>권한 · 예외 · 상태 전이</span></div><div><strong>함수 · API 계약</strong><span>입력 · 출력 · 실패 응답</span></div><div><strong>데이터 · 저장</strong><span>의미 · 관계 · 유지 범위</span></div></div><div class="figure-callout">조작과 피드백 ↔ 규칙 수정 ↔ 시안 재확인. 위에서 아래로 한 번만 내려가는 절차가 아닙니다.</div>''','폭은 추상적 탐색 범위를 표현하는 개념도이며 비용·시간·기능 수의 수치가 아닙니다. 문제·보안 제약은 시안 전에 확인하고 상세 설계는 검증된 행동에서 도출합니다.')
    result['debug']=figure('07','실패를 좁히는 다섯 개의 증거',steps([('재현','새로고침 → 문의 상태 초기화'),('관찰','메모리만 갱신, 저장 호출 없음'),('가설','지속 저장이 연결되지 않았음'),('최소 수정','합의한 저장 경로만 연결'),('재검증','원래 실패 + 정상 입력 + 저장 실패')]),'문의 예시의 가상 진단 과정입니다. 실제 과제에서는 관찰 근거로 가설을 검증합니다. 같은 증상이 항상 같은 원인이라는 뜻은 아닙니다.')
    result['cost']=figure('08','재시도 한 번이 예산을 얼마나 바꾸나요?','''<p>예시 값을 바꾸며 추가 재시도의 영향을 살펴보세요. 어떤 모델의 실제 가격·성능도 나타내지 않습니다.</p><noscript><p>JavaScript가 꺼져 있어 기본 예시의 그래프·표를 표시합니다.</p></noscript><div class="cost-controls"><label for="cost-unit">1회 시도 비용 (원)<input id="cost-unit" type="range" min="100" max="2000" step="100" value="500"><output id="cost-unit-label" for="cost-unit">500원</output></label><label for="cost-retries">추가 재시도 횟수<input id="cost-retries" type="range" min="0" max="5" step="1" value="2"><output id="cost-retries-label" for="cost-retries">2회</output></label></div><svg class="cost-chart" viewBox="0 0 600 270" role="img" aria-labelledby="cost-title cost-description"><title id="cost-title">추가 재시도 횟수에 따른 총 시도 비용</title><desc id="cost-description">교육용 선형 계산. 1회 비용 500원, 추가 재시도 2회이면 총 1500원입니다. 아래 표에서 전체 값을 읽을 수 있습니다.</desc><g class="chart-grid"><path d="M70 30V220H550 M70 125H550 M70 30H550"/></g><g class="chart-labels"><text x="64" y="224" text-anchor="end">0</text><text id="cost-y-mid" x="64" y="129" text-anchor="end">1,500</text><text id="cost-y-max" x="64" y="34" text-anchor="end">3,000</text><text x="10" y="15">원</text><text x="70" y="245">0</text><text x="166" y="245">1</text><text x="262" y="245">2</text><text x="358" y="245">3</text><text x="454" y="245">4</text><text x="550" y="245">5</text><text x="300" y="266" text-anchor="middle">추가 재시도 횟수 (회)</text></g><path class="cost-line" d="M70 188.33 L166 156.67 L262 125 L358 93.33 L454 61.67 L550 30"/><circle id="cost-point" cx="262" cy="125" r="7"/></svg><p id="cost-result" class="figure-callout" role="status">500원 × (첫 시도 1회 + 재시도 2회) = 1,500원</p><details><summary>그래프의 수치 표와 계산 조건</summary><div class="table-wrap"><table><thead><tr><th>추가 재시도</th><th>총 시도</th><th>총 비용</th></tr></thead><tbody id="cost-data"><tr><td>0회</td><td>1회</td><td>500원</td></tr><tr><td>1회</td><td>2회</td><td>1,000원</td></tr><tr><td>2회</td><td>3회</td><td>1,500원</td></tr><tr><td>3회</td><td>4회</td><td>2,000원</td></tr><tr><td>4회</td><td>5회</td><td>2,500원</td></tr><tr><td>5회</td><td>6회</td><td>3,000원</td></tr></tbody></table></div><p>각 시도 비용이 같다고 가정한 산술 모형입니다. 실제 비용에는 맥락 증가, 캐시, 도구 호출, 구독·인프라 비용 등이 영향을 줍니다. 세로축 상한은 1회 비용 × 6으로 함께 바뀝니다.</p></details>''','학습 포인트: 단가만 비교하지 말고 해결까지의 총비용과 사람의 수정 시간도 기록합니다. 재시도 수와 성공률 사이의 관계는 이 그래프에서 추정하지 않습니다.')
    result['delivery']=figure('09','네 가지 초록불을 각각 확인합니다','''<div class="gate-track"><div><span>01</span><h4>검토</h4><p>계약·변경·위험</p><small>중요한 결함이 없는가?</small></div><div><span>02</span><h4>CI</h4><p>자동 검사 결과</p><small>이 버전이 검사를 통과했는가?</small></div><div><span>03</span><h4>전달 / 배포</h4><p>목표 환경의 버전</p><small>검증한 버전이 전달되었는가?</small></div><div><span>04</span><h4>실제 사용</h4><p>핵심 흐름·저장·재실행</p><small>사용자가 결과를 얻는가?</small></div></div><div class="figure-callout">CI 성공 ≠ 배포 성공 ≠ 사용자 흐름 성공. 개인 로컬 도구는 필요한 자동 검사와 새 세션 재실행으로 확인합니다.</div>''','개념 게이트이며 실제 프로젝트의 통과 상태를 나타내지 않습니다. 체크할 항목은 프로젝트 계약에 맞춥니다. 운영형에서는 PR·머지·배포 SHA와 스모크 증거를 연결합니다.')
    result['handoff']=figure('10','완성품은 실행 파일만으로 끝나지 않습니다',steps([('실행 결과','주소 · 패키지 · 재현 명령'),('프로젝트 계약','사용자 · 범위 · 위험'),('사용 안내','준비 · 사용 · 종료 · 문제 해결'),('검증 기록','버전 · 환경 · 결과 · 미확인'),('다음 계획','제한 · 피드백 · 개선')]),'4주차 제출물 지도입니다. 다섯 개의 별도 문서가 필수라는 뜻은 아닙니다. 작은 프로젝트는 README 한 장에 함께 담아도 됩니다.')
    result['routing']=figure('11','브랜드보다 작업의 성격을 먼저 봅니다',steps([('작업 정의','기대 결과와 실패 비용'),('작게 분류','단순 편집 / 복잡한 판단 / 전문 도구'),('조합 선택','모델 · 사고 수준 · 에이전트'),('작은 실행','시간·비용 상한과 수용 조건'),('증거로 조정','충분하면 종료, 부족하면 원인에 맞춰 변경')]),'Jev와 같은 분류기를 쓸 수 있는 위치는 작업 분류입니다. 분류 결과는 권한 승인이나 정답 보장이 아니며 낮은 확신은 사람이 검토합니다.')
    result['agent-map']=figure('12','에이전트는 작업 공간에서부터 비교합니다','''<div class="completion-grid agent-spaces"><div><span>저장소 중심</span><h4>코드와 변경을 추적</h4><p>Claude Code · Codex · Grok Build</p><small>Spec → 파일 변경 → 검증 → PR</small></div><div><span>구성·확장 중심</span><h4>하네스와 모델을 조합</h4><p>Pi · Oh My Pi · OpenCode</p><small>프로바이더 · 도구 · 확장 · 권한</small></div><div><span>브라우저 제작 환경</span><h4>시안부터 게시까지</h4><p>Replit Agent</p><small>Design → Build → 실제 사용 확인</small></div><div><span>에이전트 플랫폼</span><h4>제품의 에이전트를 구성</h4><p>OnDemand</p><small>모델 · 도구 · 워크플로우 · 실행</small></div></div>''','아래 공식 조사 내용을 교육용으로 묶은 지도입니다. 제품은 여러 범주에 걸칠 수 있으며 독점 기능·성능 순위·호환 보장을 뜻하지 않습니다.')
    return result
