'use strict';
const E=FlyEngine,N=FlyController,$=id=>document.getElementById(id);let state=E.initial(2026),decision=null,busy=false,replayTimer=null;
const symbols=['','●','◆','▲','■'];
function cell(value,ghost=false){const el=document.createElement('div');el.className='cell'+(value?' c'+value:'')+(ghost?' ghost':'');el.textContent=symbols[value];return el;}
function move(){return{col:Number($('column').value),rotation:Number($('rotation').value)};}
function valid(){const m=move();return E.legal(state.boards[0]).some(x=>x.col===m.col&&x.rotation===m.rotation);}
function drawBoard(id,b,preview=false){const el=$(id);el.replaceChildren();const ghosts=new Map();if(preview&&!state.result&&valid()){const m=move(),p=E.pair(state.seed,state.round);if(m.rotation===0||m.rotation===2){ghosts.set(m.col+','+b[m.col].length,p[m.rotation===0?0:1]);ghosts.set(m.col+','+(b[m.col].length+1),p[m.rotation===0?1:0]);}else{ghosts.set(m.col+','+b[m.col].length,p[0]);const other=m.col+(m.rotation===1?1:-1);ghosts.set(other+','+b[other].length,p[1]);}}
 for(let y=E.H-1;y>=0;y--)for(let x=0;x<E.W;x++){const k=x+','+y,v=b[x][y]||ghosts.get(k)||0;el.append(cell(v,!b[x][y]&&ghosts.has(k)));}el.setAttribute('aria-label',(id==='human-board'?'사람':'회로')+' 보드: 각 열 높이 '+b.map(c=>c.length).join(', '));}
function render(){drawBoard('human-board',state.boards[0],!busy);drawBoard('neural-board',state.boards[1]);$('pair').replaceChildren(...E.pair(state.seed,state.round).map((c,i)=>{const e=cell(c);e.title=i===0?'A':'B';return e;}));$('human-score').textContent=state.cleared[0]+'개 제거';$('neural-score').textContent=state.cleared[1]+'개 제거';$('status').textContent=state.result?`${state.result} · ${state.round}라운드 종료 · 새 경기나 다시 보기를 선택하세요.`:`라운드 ${state.round+1} / ${E.LIMIT} · 열과 방향을 고르고 블록을 놓으세요.`;
 $('play').disabled=busy||!!state.result||!valid();$('replay').disabled=busy||!state.history.length;$('download').disabled=busy||!state.history.length;$('column').disabled=busy||!!state.result;$('rotation').disabled=busy||!!state.result;$('move-hint').textContent=state.result?'경기가 종료되었습니다.':valid()?'반투명 블록이 떨어질 위치입니다.':'이 배치는 공간이 부족하거나 보드 밖입니다.';
 $('history').replaceChildren(...state.history.slice().reverse().map((h,i)=>{const li=document.createElement('li');li.textContent=`${state.round-i}R · 사람 ${h.cleared[0]}개 / 회로 ${h.cleared[1]}개 제거 · 공격 ${h.attack[0]}:${h.attack[1]}`;return li;}));
 if(decision){$('activity').replaceChildren(...decision.outputs.map((count,i)=>{const row=document.createElement('div');row.className='activity-row';const label=document.createElement('span');label.textContent=`열 ${i+1}`;const track=document.createElement('div');track.className='track';const bar=document.createElement('div');bar.className='bar';bar.style.width=(count/Math.max(1,...decision.outputs)*100)+'%';track.append(bar);const value=document.createElement('span');value.textContent=count+'회 발화';row.append(label,track,value);return row;}));$('latency').textContent=`실제 계산 ${decision.elapsed_ms.toFixed(2)} ms · 모의 시간 ${decision.duration_ms} ms · 선택 ${decision.move.col+1}열 / 방향 ${decision.move.rotation} · ${N.VERSION}`;$('trace').textContent=N.circuit.channels.map(([pre,post],i)=>`열${i+1}: ${N.circuit.neurons[pre]} → ${N.circuit.neurons[post]} (${decision.rates[i]} Hz)`).join('\n')+'\n\n발화 (최대 300개)\n'+decision.trace.map(([t,i])=>`${t.toFixed(1)} ms  ${N.circuit.neurons[i]}`).join('\n');}
}
$('column').onchange=render;$('rotation').onchange=render;
$('play').onclick=()=>{try{const p=E.pair(state.seed,state.round);decision=N.choose(state.boards[1],p,(state.seed+state.round*101)>>>0);state=E.step(state,[move(),decision.move]);render();}catch(e){$('status').textContent='진행 중단: '+e.message+' 기준선 봇으로 자동 교체하지 않습니다.';$('play').disabled=true;}};
$('start').onclick=()=>{const seed=Number($('seed').value);if($('seed').value.trim()===''||!Number.isInteger(seed)||seed<0||seed>4294967295){$('status').textContent='시드는 0부터 4294967295까지의 정수로 입력하세요.';return;}clearTimeout(replayTimer);busy=false;state=E.initial(seed);decision=null;$('activity').textContent='첫 수를 놓으면 회로의 발화를 볼 수 있습니다.';$('trace').textContent='새 경기입니다.';$('latency').textContent='';render();};
$('replay').onclick=()=>{const history=state.history.slice(),seed=state.seed;state=E.initial(seed);decision=null;busy=true;let i=0;function tick(){try{if(i<history.length){decision=N.choose(state.boards[1],E.pair(seed,state.round),(seed+state.round*101)>>>0);state=E.step(state,history[i++].moves);render();$('status').textContent=`다시 보기 · ${i} / ${history.length} 라운드`;replayTimer=setTimeout(tick,350);}else{busy=false;render();$('status').textContent+=' · 저장한 수로 재생을 완료했습니다.';}}catch(e){busy=false;$('status').textContent='재생 실패: '+e.message;}}tick();};
$('download').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,controller:N.VERSION,dataset:N.circuit.revision,state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='flyblock-'+state.seed+'-replay.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('evaluate').onclick=()=>{$('evaluate').disabled=true;$('evaluation').textContent='실제 회로 경기를 계산하고 있습니다…';setTimeout(()=>{try{const rows=N.evaluate(20),table=document.createElement('table'),head=document.createElement('tr');for(const label of ['상대 기준선','승 / 무 / 패','실패','중앙 지연']){const th=document.createElement('th');th.textContent=label;head.append(th);}table.append(head);for(const r of rows){const tr=document.createElement('tr');for(const value of [r.baseline==='random'?'무작위 합법 수':'낮은 높이 우선',`${r.win} / ${r.draw} / ${r.loss}`,r.failures,(r.median_ms??0).toFixed(2)+' ms']){const td=document.createElement('td');td.textContent=value;tr.append(td);}table.append(tr);}$('evaluation').replaceChildren(table);}catch(e){$('evaluation').textContent='측정 실패: '+e.message;}finally{$('evaluate').disabled=false;}},30);};render();
