'use strict';
const E=FlyEngine,N=FlyController,R=FlyRealtime,I=FlyInput,$=id=>document.getElementById(id),surface=$('game');
let state=R.initial(2026),pending=[],replayLog=null,replayIndex=0,replayFinished=false,pauseReason='',renderKey='',activityKey='';
const symbols=['','●','◆','▲','■'];
function cell(value,kind=''){const el=document.createElement('div');el.className='cell'+(value?' c'+value:'')+(kind?' '+kind:'');el.textContent=symbols[value];return el;}
function drawBoard(id,i){const b=state.boards[i],p=state.active[i],active=new Map(),ghost=new Map();if(p){R.cells(p).forEach(([x,y,c])=>active.set(x+','+y,c));R.cells(R.landing(b,p)).forEach(([x,y,c])=>ghost.set(x+','+y,c));}const fragment=document.createDocumentFragment();for(let y=E.H-1;y>=0;y--)for(let x=0;x<E.W;x++){const k=x+','+y,a=active.get(k),g=ghost.get(k),v=a||b[x][y]||g||0;fragment.append(cell(v,a?'falling':!b[x][y]&&g?'ghost':''));}$(id).replaceChildren(fragment);$(id).setAttribute('aria-label',(i===0?'사람':'회로')+' 보드: 열 높이 '+b.map(c=>c.length).join(', ')+(p?`; 낙하 블록 ${p.x+1}열, 바닥에서 ${p.y+1}칸`:''));}
function announce(){const phase=state.phase;let message='경기 시작을 누르세요. 시작 전에는 블록이 떨어지지 않습니다.';if(replayFinished)message=`활성 플레이 ${(state.tick*R.TICK_MS/1000).toFixed(1)}초의 타이밍 재생을 완료했습니다.`;else if(phase==='error')message='오류로 중단했습니다: '+state.error+' · 다른 봇으로 교체하지 않습니다.';else if(phase==='ended')message=`${state.result} · 사람 ${state.cleared[0]}개 / 회로 ${state.cleared[1]}개 제거. 새 경기를 시작할 수 있습니다.`;else if(phase==='paused')message=(pauseReason||'일시정지했습니다.')+' 계속하려면 P 또는 재개를 누르세요.';else if(phase==='running')message=replayLog?'타이밍 리플레이 중입니다. 실시간 입력은 차단됩니다.': '← → 이동 · ↑ 회전 · ↓ 빠르게 · Space 즉시 낙하. 게임 영역 안에서 키보드를 사용하세요.';if($('status').textContent!==message)$('status').textContent=message;}
function render(force=false){const key=[state.tick,state.phase,state.turns.join(','),replayFinished,!!replayLog].join(':');if(!force&&key===renderKey)return;renderKey=key;drawBoard('human-board',0);drawBoard('neural-board',1);for(const [i,name]of ['human','neural'].entries()){$(name+'-score').textContent=state.cleared[i]+'개 제거';$(name+'-pending').textContent='대기 공격 '+state.pending[i];$(name+'-next').replaceChildren(...E.pair(state.seed,state.turns[i]+1).map(c=>cell(c)));}
 const seconds=Math.max(0,Math.ceil((R.MAX_TICKS-state.tick)*R.TICK_MS/1000));$('timer').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');$('mode').textContent=replayFinished?'REPLAY COMPLETE':replayLog?'REPLAY · '+state.phase.toUpperCase():state.phase.toUpperCase();$('start').textContent=state.phase==='ready'?'경기 시작':'새 경기';$('pause').disabled=!['running','paused'].includes(state.phase)||replayFinished;$('pause').textContent=state.phase==='paused'?'재개 · P':'일시정지 · P';$('replay').disabled=state.tick===0||state.phase==='error';$('download').disabled=state.tick===0;document.querySelectorAll('[data-action]').forEach(b=>b.disabled=state.phase!=='running'||!!replayLog);
 $('history').replaceChildren(...state.locks.slice(-12).reverse().map(h=>{const li=document.createElement('li');li.textContent=`${(h.tick*R.TICK_MS/1000).toFixed(1)}초 · ${h.player===0?'사람':'회로'} · ${h.cleared}개 제거 / ${h.chains}연쇄 / 공격${h.attack}`;return li;}));
 if(state.decision){const d=state.decision,k=state.turns[1]+':'+d.move.col+':'+d.move.rotation;if(k!==activityKey){activityKey=k;$('activity').replaceChildren(...d.outputs.map((count,i)=>{const row=document.createElement('div');row.className='activity-row';const label=document.createElement('span');label.textContent=`열 ${i+1}`;const track=document.createElement('div');track.className='track';const bar=document.createElement('div');bar.className='bar';bar.style.width=count/Math.max(1,...d.outputs)*100+'%';track.append(bar);const value=document.createElement('span');value.textContent=count+'회 발화';row.append(label,track,value);return row;}));$('latency').textContent=`계산 ${state.lastComputeMs.toFixed(2)} ms · 목표 ${d.move.col+1}열 / 방향 ${d.move.rotation} · 모의시간 ${d.duration_ms} ms`;$('trace').textContent=N.circuit.channels.map(([pre,post],i)=>`열${i+1}: ${N.circuit.neurons[pre]} → ${N.circuit.neurons[post]} (${d.rates[i]} Hz)`).join('\n')+'\n\n발화 (최대300개)\n'+d.trace.map(([t,i])=>`${t.toFixed(1)} ms  ${N.circuit.neurons[i]}`).join('\n');}}
 announce();}
function stopWithError(e){clock.stop();pending=[];R.error(state,e.message||String(e));render(true);}
function tick(){try{if(state.phase!=='running')return false;if(replayLog&&state.tick>=replayLog.endTick){replayFinished=true;R.pause(state);return false;}let actions;if(replayLog){actions=[];while(replayLog.actions[replayIndex]?.tick===state.tick+1)actions.push(replayLog.actions[replayIndex++].action);}else{actions=pending;pending=[];}R.advance(state,actions);if(replayLog&&state.tick>=replayLog.endTick){replayFinished=true;R.pause(state);return false;}return state.phase==='running';}catch(e){stopWithError(e);return false;}}
const clock=I.clock({request:fn=>requestAnimationFrame(fn),cancel:id=>cancelAnimationFrame(id),step:tick,render,onLag:()=>pause('프레임 지연으로 일시정지했습니다.'),dt:R.TICK_MS});
function pause(reason){if(state.phase!=='running')return;clock.stop();pending=[];R.pause(state);pauseReason=reason;render(true);}
function togglePause(){if(replayFinished)return;if(state.phase==='running')pause('일시정지했습니다.');else if(state.phase==='paused'){surface.focus({preventScroll:true});pauseReason='';R.resume(state);clock.start();render(true);}}
function act(action){if(action==='pause'){togglePause();return;}if(state.phase==='running'&&!replayLog)pending.push(action);}
window.addEventListener('keydown',event=>{const result=I.key(event,surface.contains(document.activeElement),state.phase,!!replayLog);if(result.handled){event.preventDefault();if(result.action)act(result.action);}});
surface.addEventListener('pointerdown',event=>{if(!event.target.closest('button,input,select,a,summary'))surface.focus({preventScroll:true});});surface.addEventListener('focusout',event=>{if(!surface.contains(event.relatedTarget))pause('게임 영역을 벗어나 일시정지했습니다.');});window.addEventListener('blur',()=>pause('다른 창으로 이동해 일시정지했습니다.'));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause('페이지가 숨겨져 일시정지했습니다.');});
document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>{surface.focus({preventScroll:true});act(button.dataset.action);}));$('pause').onclick=togglePause;
function clearSession(){clock.stop();pending=[];replayLog=null;replayIndex=0;replayFinished=false;pauseReason='';renderKey='';activityKey='';}
$('start').onclick=()=>{const value=$('seed').value,seed=Number(value);if(value.trim()===''||!Number.isInteger(seed)||seed<0||seed>4294967295){$('status').textContent='시드는 0부터 4294967295까지 정수로 입력하세요.';return;}clearSession();try{state=R.start(seed);surface.focus({preventScroll:true});clock.start();render(true);}catch(e){stopWithError(e);}};
$('replay').onclick=()=>{const log=replayLog||R.recording(state);clearSession();try{R.validateReplay(log);replayLog=log;state=R.start(log.seed);surface.focus({preventScroll:true});clock.start();render(true);}catch(e){stopWithError(e);}};
$('download').onclick=()=>{const log=replayLog||R.recording(state),blob=new Blob([JSON.stringify(log,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='flyblock-realtime-'+log.seed+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};render(true);
