"""Download pinned public v783 data and extract a deterministic real induced circuit.
python3 -m pip install pyarrow==25.0.1
python3 prepare.py --source /tmp/flyblock-connectivity-783.parquet
"""
import argparse,hashlib,json,pathlib,urllib.request
import pyarrow.parquet as pq
import pyarrow.compute as pc
REV='91bdd1e7dcf193f3e7ca5a8933497fcef63b7960'
BASE='https://raw.githubusercontent.com/philshiu/Drosophila_brain_model/'+REV+'/'
p=argparse.ArgumentParser();p.add_argument('--source',default='/tmp/flyblock-connectivity-783.parquet');a=p.parse_args()
src=pathlib.Path(a.source)
if not src.exists():urllib.request.urlretrieve(BASE+'Connectivity_783.parquet',src)
expected='efeb23fb99098e9c390f6869969b2a121a2ee92c833cfc45ecb2c1d8e1af0347'
assert hashlib.sha256(src.read_bytes()).hexdigest()==expected, 'Pinned source SHA256 mismatch'
t=pq.read_table(src,columns=['Presynaptic_ID','Postsynaptic_ID','Connectivity','Excitatory x Connectivity'])
# Top positive signed edges; deterministic ties by IDs. Six disjoint pairs prevent channel overlap.
strong=t.filter(pc.greater_equal(t['Excitatory x Connectivity'],200)).to_pylist()
strong.sort(key=lambda r:(-r['Excitatory x Connectivity'],r['Presynaptic_ID'],r['Postsynaptic_ID']))
ids=[];channels=[]
for r in strong:
 pre,post=r['Presynaptic_ID'],r['Postsynaptic_ID']
 if pre==post or pre in ids or post in ids:continue
 ids.extend([pre,post]);channels.append([pre,post])
 if len(channels)==6:break
assert len(channels)==6
mask=pc.and_(pc.is_in(t['Presynaptic_ID'],value_set=__import__('pyarrow').array(ids)),pc.is_in(t['Postsynaptic_ID'],value_set=__import__('pyarrow').array(ids)))
rows=t.filter(mask).to_pylist();rows.sort(key=lambda r:(r['Presynaptic_ID'],r['Postsynaptic_ID']))
d={'revision':REV,'dataset':'FlyWire v783 / Connectivity_783.parquet','source':BASE+'Connectivity_783.parquet','source_sha256':hashlib.sha256(src.read_bytes()).hexdigest(),'source_rows':t.num_rows,'license':'MIT (repository LICENSE; vendored)','selection':'Six strongest positive edges with disjoint neuron IDs; induced directed subgraph, unmodified signed counts; no anatomical task interpretation','neurons':[str(i) for i in ids],'channels':[[ids.index(pre),ids.index(post)] for pre,post in channels],'edges':[[ids.index(r['Presynaptic_ID']),ids.index(r['Postsynaptic_ID']),r['Excitatory x Connectivity']] for r in rows]}
out=pathlib.Path(__file__).parent/'data';out.mkdir(exist_ok=True)
text=json.dumps(d,ensure_ascii=False,indent=2)+'\n';(out/'circuit.json').write_text(text);(out/'circuit.js').write_text('/* Generated by prepare.py; real pinned connectivity, see circuit.json. */\n(function(root){const data='+text.strip()+'; if(typeof module!=="undefined")module.exports=data;else root.FlyCircuit=data;})(globalThis);\n')
print(json.dumps({'neurons':len(ids),'edges':len(rows),'channels':channels,'source_sha256':d['source_sha256']},indent=2))
